name: esp_provisioning
description: Espressif Provisioning library
version: 1.0.0+6
homepage: https://github.com/sunshine-tech/esp_provisioning.git

# environment:
#   sdk: ">=2.7.0 <3.0.0"
#   flutter: ">=1.10.0"
environment:
  sdk: ">=2.16.0 <3.0.0"
  # flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.1.0
  cryptography: ^2.0.5
  cryptography_flutter: ^2.0.2
  collection: ^1.15.0
  flutter_blue: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.tuanpm.esp_provisioning
        pluginClass: EspProvisioningPlugin
      ios:
        pluginClass: EspProvisioningPlugin
